<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
	<TreatWarningsAsErrors>false</TreatWarningsAsErrors>


  </PropertyGroup>

  <ItemGroup>
    <None Remove="Image.jpeg" />
    <None Remove="Views\Profile_picture.jpeg" />
    <None Remove="Views\SlideShow1.jpeg" />
    <None Remove="Views\SlideShow2.jpeg" />
    <None Remove="Views\SLideShow3.jpeg" />
  </ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="Ban3.Infrastructures.NetMail" Version="1.0.5" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="LiveCharts.Wpf" Version="0.9.7" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.13" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.13" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="OxyPlot.Wpf" Version="2.2.0" />
		<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="8.0.3" />
		<PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
	</ItemGroup>
	
	<ItemGroup>
	  <Page Include="App.xaml" />
	</ItemGroup>
	
	<ItemGroup>
	  <Resource Include="Views\Image.jpeg" />
	  <Resource Include="Views\Profile_picture.jpeg">
	    <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Views\SlideShow1.jpeg" />
	  <Resource Include="Views\SlideShow2.jpeg" />
	  <Resource Include="Views\SLideShow3.jpeg" />
	</ItemGroup>

</Project>
